"""Lebanese cities, towns, and neighborhoods mapped to governorates.

Used to seed DeliveryLocality rows. Existing Order.city free-text values are
never rewritten — only new checkouts use these structured localities.
"""

# (name, optional aliases shown as separate searchable rows pointing to same gov)
# Aliases are stored as their own locality rows with the same governorate so
# customers can find common spellings (e.g. Aramol / Aaramoun).

LOCALITIES_BY_GOVERNORATE = {
    "Beirut": [
        "Beirut",
        "Achrafieh",
        "Ain El Mreisseh",
        "Bachoura",
        "Badaro",
        "Clemenceau",
        "Gemmayzeh",
        "Hamra",
        "Mar Mikhael",
        "Mazraa",
        "Medawar",
        "Mina El Hosn",
        "Moussaitbeh",
        "Port of Beirut",
        "Raouche",
        "Ras Beirut",
        "Ras El Nabaa",
        "Rmeil",
        "Saifi",
        "Tallet El Khayat",
        "Verdun",
        "Zokak El Blat",
    ],
    "Mount Lebanon": [
        # Aley / Aramoun area (common misspellings included)
        "Aaramoun",
        "Aramoun",
        "Aramol",
        "Aley",
        "Bchamoun",
        "Bhamdoun",
        "Bsous",
        "Chanay",
        "Charoun",
        "Chartoun",
        "Comayel",
        "Einab",
        "Kahale",
        "Kayfoun",
        "Keyfoun",
        "Majdel Baana",
        "Mansourieh Aley",
        "Qmatiyeh",
        "Ramlieh",
        "Rechmaya",
        "Saoufar",
        "Sofar",
        "Souk El Gharb",
        # Baabda / southern suburbs
        "Baabda",
        "Hadath",
        "Hazmieh",
        "Furn El Chebbak",
        "Chiyah",
        "Ghobeiry",
        "Haret Hreik",
        "Bourj El Barajneh",
        "Mreijeh",
        "Laylake",
        "Bir Hassan",
        "Ouzaï",
        "Ouzai",
        "Jnah",
        "Khalde",
        "Aramoun Khalde",
        "Choueifat",
        "Wadi Chahrour",
        "Falougha",
        "Hammana",
        "Qornayel",
        "Tarchich",
        "Ras El Matn",
        "Broummana",
        "Beit Mery",
        "Monteverde",
        "Mansourieh El Matn",
        "Mansourieh",
        "Mkalles",
        "Dekwaneh",
        "Sin El Fil",
        "Jdeideh",
        "Bauchrieh",
        "Fanar",
        "Ain Saadeh",
        "Ain El Remmaneh",
        "Beit Chabab",
        "Bikfaya",
        "Dhour El Choueir",
        "Mrouj",
        "Bteghrine",
        "Qanat Bakish",
        "Zaarour",
        # Metn / Keserwan / Jbeil
        "Antelias",
        "Dbayeh",
        "Zalka",
        "Jal El Dib",
        "Naccache",
        "Rabieh",
        "Rawda",
        "Zouk Mosbeh",
        "Zouk Mikael",
        "Jeita",
        "Ajaltoun",
        "Ballouneh",
        "Ghosta",
        "Faraya",
        "Faqra",
        "Kfardebian",
        "Jounieh",
        "Sarba",
        "Ghadir",
        "Haret Sakhr",
        "Adonis",
        "Tabarja",
        "Bouar",
        "Safra",
        "Adma",
        "Ghazir",
        "Maameltein",
        "Kaslik",
        "Jbeil",
        "Byblos",
        "Amchit",
        "Blat",
        "Halat",
        "Ehmej",
        "Lassa",
        "Afqa",
        "Laqlouq",
        "Kartaba",
        "Qartaba",
        # Chouf
        "Chouf",
        "Deir El Qamar",
        "Beiteddine",
        "Beit Eddine",
        "Mukhtara",
        "Barouk",
        "Maasser El Chouf",
        "Baakline",
        "Baaqline",
        "Joun",
        "Damour",
        "Jiyeh",
        "Rmeileh",
        "Naameh",
        "Haret El Naameh",
        "Dibbiyeh",
        "Ketermaya",
        "Barja",
        "Chhim",
        "Zaarouriyeh",
        "Mazraat El Chouf",
        "Ain Zhalta",
        "Bater",
        "Niha Chouf",
        # Other Mount Lebanon
        "Dahye",
        "Dahiyeh",
        "Dahieh",
        "Southern Suburbs",
        "Bsalim",
        "Roumieh",
        "Qornet Chehwan",
        "Beit El Chaar",
        "Cornet Chahwan",
        "Ain Aar",
        "Mazraat Yachoua",
        "Bhannes",
        "Douar",
        "Mar Chaaya",
        "Saqiet El Misk",
        "Bikfaya Mhaydseh",
        "Salima",
        "Qaaqour",
        "Baskinta",
        "Qornayel",
    ],
    "North": [
        "Tripoli",
        "El Mina",
        "Mina",
        "Qalamoun",
        "Beddawi",
        "Abou Samra",
        "Zgharta",
        "Ehden",
        "Miziara",
        "Kfar Sghab",
        "Bcharre",
        "Bsharri",
        "Hasroun",
        "Diman",
        "Hadath El Jebbeh",
        "Koura",
        "Amioun",
        "Kousba",
        "Batroun",
        "Chekka",
        "Heri",
        "Ras Chekka",
        "Anfeh",
        "Enfeh",
        "Kfar Abida",
        "Douma",
        "Tannourine",
        "Hardine",
        "Miniyeh",
        "Danniyeh",
        "Sir El Danniyeh",
        "Bhannine",
        "Kfar Habou",
        "Ras Maska",
        "Qalamoun",
        "Deddeh",
        "Kefraya Koura",
        "Bsarma",
        "Fiaa",
        "Btouroura",
        "Barsa",
        "Bechmezzine",
        "Kfaraakka",
        "Nakhle",
        "Ijdabra",
        "Kfarhazir",
        "Daraya",
        "Batroumine",
    ],
    "Akkar": [
        "Halba",
        "Akkar",
        "Qoubaiyat",
        "Kobayat",
        "Bebnine",
        "Abdeh",
        "Berkayel",
        "Fnaydek",
        "Andqet",
        "Machha",
        "Rahbeh",
        "Bire Akkar",
        "Tal Abbas",
        "Saadine",
        "Wadi Khaled",
        "Hissa",
        "Qobayat",
        "Aydamoun",
        "Kfartoun",
        "Beino",
        "Akroum",
        "Chadra",
        "Qbaiyat",
        "Miniara",
        "Machha",
        "Bzal",
        "Khreibet Ej Jindi",
        "Sheikh Zennad",
        "Qleiaat",
        "Klayat",
        "Aboudiyeh",
        "Hokr El Dahri",
        "Sahel Akkar",
        "Tal Bire",
        "Tal Mehyan",
    ],
    "Beqaa": [
        "Zahle",
        "Zahlé",
        "Chtaura",
        "Jdita",
        "Taalabaya",
        "Saadnayel",
        "Majdal Anjar",
        "Anjar",
        "Barelias",
        "Bar Elias",
        "Rayak",
        "Riyaq",
        "Qabb Elias",
        "Kab Elias",
        "Mreijat",
        "Taanayel",
        "Ferzol",
        "Niha Zahlé",
        "Ablah",
        "Kfarzabad",
        "Terbol",
        "Riyak",
        "West Beqaa",
        "Joub Jannine",
        "Kamed El Loz",
        "Machghara",
        "Saghbine",
        "Qaraoun",
        "Lala",
        "Sohmor",
        "Yohmor",
        "Rachaya",
        "Rachaya El Wadi",
        "Hasbaya Beqaa",
        "Kfar Qouq",
        "Ain Ata",
        "Mdoukha",
        "Khirbet Rouha",
        "Dahr El Ahmar",
    ],
    "Baalbek-Hermel": [
        "Baalbek",
        "Baalbeck",
        "Hermel",
        "Labweh",
        "Brital",
        "Nabi Chit",
        "Taraya",
        "Temnine",
        "Chmistar",
        "Bednayel",
        "Bouday",
        "Iaat",
        "Douris",
        "Nahle",
        "Younine",
        "Harbata",
        "Qaa",
        "Fekehe",
        "Ras Baalbek",
        "Deir El Ahmar",
        "Boudai",
        "Shmustar",
        "Ali Nahri",
        "Hizzine",
        "Serain",
        "Jabbouleh",
        "Zabboud",
        "Qasr",
        "Chouaghir",
        "Fissane",
        "Kouakh",
        "Zighrine",
        "Hawch Barada",
        "Aarsal",
        "Arsal",
    ],
    "South": [
        "Saida",
        "Sidon",
        "Tyre",
        "Sour",
        "Jezzine",
        "Nabatieh South",
        "Ghazieh",
        "Maghdouche",
        "Maghdousheh",
        "Zrariyeh",
        "Sarafand",
        "Zahrani",
        "Ansariyeh",
        "Adloun",
        "Aadloun",
        "Abra",
        "Hlaliyeh",
        "Miye ou Miye",
        "Villat Saida",
        "Ein El Hilweh",
        "Qana",
        "Qana El Jalil",
        "Abbassiyeh",
        "Bazouriyeh",
        "Burj El Shemali",
        "Maachouk",
        "Rachidiyeh",
        "Jwaya",
        "Tebnine",
        "Bent Jbeil",
        "Bint Jbeil",
        "Aitaroun",
        "Ainata",
        "Rmeish",
        "Rmeich",
        "Ain Ebel",
        "Yaroun",
        "Maroun El Ras",
        "Blida",
        "Houla",
        "Meiss El Jabal",
        "Markaba",
        "Kfar Kila",
        "Odaisseh",
        "Alma El Chaab",
        "Naqoura",
        "Naqura",
        "Chebaa",
        "Shebaa",
        "Hasbaya",
        "Marjayoun",
        "Marjeyoun",
        "Khiam",
        "El Khiam",
        "Deir Mimas",
        "Ibl El Saqi",
        "Kfar Chouba",
        "Rachaya El Foukhar",
        "Bkassine",
        "Lebaa",
        "Rihane",
        "Aarye",
        "Kfar Falous",
        "Midane",
        "Louaizeh",
        "Wadi Jezzine",
        "Aichiyeh",
        "Sfaray",
        "Roum",
        "Kfarhouna",
        "Machmoucheh",
        "Anane",
        "Bteddine El Leqch",
    ],
    "Nabatieh": [
        "Nabatieh",
        "Nabatiyeh",
        "Kfar Remman",
        "Kfar Roummane",
        "Arnoun",
        "Jbaa",
        "Houmine",
        "Habbouch",
        "Ansar",
        "Zefta",
        "Mayfadoun",
        "Kfar Tibnit",
        "Deir El Zahrani",
        "Jarjouaa",
        "Arab Salim",
        "Ain Qana",
        "Sir El Gharbiyeh",
        "Doueir",
        "Qsaibe",
        "Zebdine",
        "Kfar Sir",
        "Harouf",
        "Charqiyeh",
        "Insar",
        "Kfarfila",
        "Aabbassiyeh Nabatieh",
        "Qaaqaiyet El Jisr",
        "Yohmor Nabatieh",
        "Braike",
        "Toul",
        "Choukine",
        "Zebdine",
        "Jibchit",
        "Kfour",
        "Souratiyeh",
        "Aadayseh",
        "Blat Nabatieh",
        "Deir Qanoun",
    ],
}
