# Generated by Django 5.0.2 on 2026-07-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Safa Style', max_length=120)),
                ('tagline', models.CharField(default='Modest. Modern. Made for you.', max_length=255)),
                ('about', models.TextField(blank=True, default="Your new Beirut-based fashion go-to. We're famous for redefining modest minimalism with a trend-forward approach, all while maintaining top notch quality, comfort, and most importantly, aesthetic.")),
                ('address', models.CharField(default='Beirut - Airport Highway - Ziad Rahbani Avenue', max_length=255)),
                ('phone_boutique', models.CharField(default='81 820 915 / 01 820 915', max_length=80)),
                ('phone_shoes', models.CharField(default='76 902 823', max_length=80)),
                ('email', models.EmailField(default='info@safastyle.com', max_length=254)),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/safastyleboutique/')),
                ('instagram_handle', models.CharField(default='@safastyleboutique', max_length=80)),
                ('currency_symbol', models.CharField(default='$', max_length=8)),
                ('default_country', models.CharField(default='Lebanon', max_length=80)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
