# Generated by Django 5.0.2 on 2026-07-27 13:54

import django.db.models.deletion
from decimal import Decimal

from django.db import migrations, models
def seed_governorates(apps, schema_editor):
    Governorate = apps.get_model("orders", "Governorate")
    rows = (
        ("Akkar", Decimal("5"), 1),
        ("Baalbek-Hermel", Decimal("5"), 2),
        ("Beirut", Decimal("4"), 3),
        ("Beqaa", Decimal("5"), 4),
        ("Mount Lebanon", Decimal("5"), 5),
        ("Nabatieh", Decimal("5"), 6),
        ("North", Decimal("5"), 7),
        ("South", Decimal("5"), 8),
    )
    for name, fee, sort in rows:
        Governorate.objects.update_or_create(
            name=name,
            defaults={"delivery_fee": fee, "sort_order": sort, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Governorate',
                'verbose_name_plural': 'Governorates',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='governorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.governorate'),
        ),
        migrations.RunPython(seed_governorates, migrations.RunPython.noop),
    ]
