# Generated by Django 5.0.2 on 2026-08-09 19:11

import django.db.models.deletion
from django.db import migrations, models


def seed_localities(apps, schema_editor):
    """Seed towns/neighborhoods. Does not touch existing Order rows."""
    from orders.localities import LOCALITIES_BY_GOVERNORATE

    Governorate = apps.get_model("orders", "Governorate")
    DeliveryLocality = apps.get_model("orders", "DeliveryLocality")

    gov_by_name = {g.name: g for g in Governorate.objects.all()}
    for gov_name, names in LOCALITIES_BY_GOVERNORATE.items():
        gov = gov_by_name.get(gov_name)
        if not gov:
            continue
        seen = set()
        for sort, name in enumerate(names):
            key = name.strip()
            if not key or key.lower() in seen:
                continue
            seen.add(key.lower())
            DeliveryLocality.objects.update_or_create(
                name=key,
                governorate=gov,
                defaults={"is_active": True, "sort_order": sort},
            )


def unseed_localities(apps, schema_editor):
    DeliveryLocality = apps.get_model("orders", "DeliveryLocality")
    DeliveryLocality.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_governorates_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(help_text='Town / city name (copied from locality for Lebanon checkouts).', max_length=120),
        ),
        migrations.CreateModel(
            name='DeliveryLocality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='orders.governorate')),
            ],
            options={
                'verbose_name': 'Delivery locality',
                'verbose_name_plural': 'Delivery localities',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.deliverylocality'),
        ),
        migrations.AddConstraint(
            model_name='deliverylocality',
            constraint=models.UniqueConstraint(fields=('name', 'governorate'), name='unique_locality_name_per_governorate'),
        ),
        migrations.RunPython(seed_localities, unseed_localities),
    ]
