# Generated by Django 5.0.2 on 2026-08-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delivery_localities'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('awaiting', 'Awaiting payment'), ('paid', 'Paid'), ('failed', 'Failed / expired'), ('refunded', 'Refunded')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='whish_collect_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='whish_external_id',
            field=models.CharField(blank=True, db_index=True, help_text='Idempotent reference sent to Whish Pay.', max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='whish_payer_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on delivery'), ('whish', 'Whish Pay')], default='cod', max_length=40),
        ),
    ]
